name:                cryptopals
version:             0.1.0.0
github:              "tbtommyb/cryptopals"
license:             BSD3
author:              "Tom Johnson"
maintainer:          "tom@tmjohnson.co.uk"
copyright:           "2020 Tom Johnson"

ghc-options: -Wall

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cryptopals#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- base64-bytestring
- base16-bytestring
- utf8-string
- hashmap
- cryptocipher
- containers

library:
  source-dirs: src

executables:
  cryptopals-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptopals

tests:
  cryptopals-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptopals
    defaults: hspec/hspec@master
